export const stylesKonto = {
  container: {
    padding: '30px',
    maxWidth: '800px',
    margin: '0 auto',
    backgroundColor: '#111111',
    borderRadius: '15px',
    border: '1px solid #333',
    color: '#ffffff',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    marginBottom: '30px',
    paddingBottom: '20px',
    borderBottom: '2px solid #333',
  },
  avatar: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    backgroundColor: '#3498db',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '36px',
    fontWeight: 'bold',
    color: 'white',
  },
  nazwaUzytkownika: {
    fontSize: '28px',
    fontWeight: '600',
  },
  badge: {
    backgroundColor: '#27ae60',
    color: 'white',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '12px',
    display: 'inline-block',
    marginLeft: '10px',
  },
  sekcja: {
    backgroundColor: '#1a1a1a',
    borderRadius: '10px',
    padding: '20px',
    marginBottom: '20px',
    border: '1px solid #333',
  },
  tytulSekcji: {
    fontSize: '18px',
    fontWeight: '600',
    marginBottom: '15px',
    color: '#ffffff',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  gridStatystyk: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '15px',
  },
  kartaStatystyki: {
    backgroundColor: '#1a1a1a',
    padding: '15px',
    borderRadius: '8px',
    textAlign: 'center',
  },
  wartoscStatystyki: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#3498db',
    marginBottom: '5px',
  },
  etykietaStatystyki: {
    fontSize: '12px',
    color: '#999',
    textTransform: 'uppercase',
  },
  formularz: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  poleFormularza: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  label: {
    fontSize: '14px',
    color: '#ccc',
  },
  input: {
    padding: '10px',
    backgroundColor: '#222',
    border: '1px solid #444',
    borderRadius: '5px',
    color: 'white',
    fontSize: '16px',
  },
  inputDisabled: {
    backgroundColor: '#1a1a1a',
    color: '#666',
    cursor: 'not-allowed',
  },
  przycisk: {
    padding: '12px 24px',
    backgroundColor: '#3498db',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.3s',
    marginRight: '10px',
  },
  przyciskLogout: {
    padding: '12px 24px',
    backgroundColor: '#e74c3c',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.3s',
  },
  przyciskAnuluj: {
    padding: '12px 24px',
    backgroundColor: '#7f8c8d',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  akcje: {
    display: 'flex',
    gap: '10px',
    justifyContent: 'flex-end',
    marginTop: '20px',
  },
  infoTekst: {
    color: '#999',
    fontSize: '14px',
    marginTop: '5px',
  },
  linia: {
    height: '1px',
    backgroundColor: '#333',
    margin: '20px 0',
  },
};